// <auto-generated />
using System;
using DAA.Database.Migrations.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAA.Database.Migrations.Migrations
{
    [DbContext(typeof(DAADbContext))]
    [Migration("20211003164305_CreateBaseViews")]
    partial class CreateBaseViews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAA.Database.Models.DataTables.DatatablesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DRS_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DRS_Code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DataTablesTableId")
                        .HasColumnType("int")
                        .HasColumnName("DTS_Id");

                    b.Property<string>("DefaultFrom")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DRS_DefaultFrom");

                    b.Property<string>("DefaultTo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DRS_DefaultTo");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DRS_DefaultValue");

                    b.Property<bool>("HasFilter")
                        .HasColumnType("bit")
                        .HasColumnName("DRS_HasFilter");

                    b.Property<bool>("IsBasic")
                        .HasColumnType("bit")
                        .HasColumnName("DRS_IsBasic");

                    b.Property<bool>("IsRange")
                        .HasColumnType("bit")
                        .HasColumnName("DRS_IsRange");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DRS_Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("DRS_Order");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("DRS_Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_UpdatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("DataTablesTableId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("DATATABLES_RECORDS");
                });

            modelBuilder.Entity("DAA.Database.Models.DataTables.DatatablesTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DTS_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DTS_Code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DTS_Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DTS_Name");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DTS_Reference");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_UpdatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Reference");

                    b.ToTable("DATATABLES_TABLES");
                });

            modelBuilder.Entity("DAA.Database.Models.Platforms.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PTS_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PTS_Company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PTS_Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("MONEY")
                        .HasColumnName("PTS_Price");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PTS_ReleaseDate");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_UpdatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("PLATFORMS");
                });

            modelBuilder.Entity("DAA.Database.Models.VideoGames.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VGS_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VGS_Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("VGS_Name");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("PTS_Id");

                    b.Property<decimal>("Price")
                        .HasColumnType("MONEY")
                        .HasColumnName("VGS_Price");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("VGS_ReleaseDate");

                    b.Property<decimal>("Score")
                        .HasColumnType("NUMERIC(3,2)")
                        .HasColumnName("VGS_Score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUT_UpdatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PlatformId");

                    b.HasIndex("Price");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("Score");

                    b.ToTable("VIDEO_GAMES");
                });

            modelBuilder.Entity("DAA.Database.Views.VideoGameScore", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlatformName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VideoGameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("VW_VIDEOGAMESCORE");
                });

            modelBuilder.Entity("DAA.Database.Models.DataTables.DatatablesRecord", b =>
                {
                    b.HasOne("DAA.Database.Models.DataTables.DatatablesTable", "DatatablesTable")
                        .WithMany("DatatablesRecords")
                        .HasForeignKey("DataTablesTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatatablesTable");
                });

            modelBuilder.Entity("DAA.Database.Models.VideoGames.VideoGame", b =>
                {
                    b.HasOne("DAA.Database.Models.Platforms.Platform", "Platform")
                        .WithMany("VideoGames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("DAA.Database.Models.DataTables.DatatablesTable", b =>
                {
                    b.Navigation("DatatablesRecords");
                });

            modelBuilder.Entity("DAA.Database.Models.Platforms.Platform", b =>
                {
                    b.Navigation("VideoGames");
                });
#pragma warning restore 612, 618
        }
    }
}
